site_name: Task Tracker App
nav:
  - Home: index.md
  - Introduction: Introduction.md
  - Scope: scope.md
  - Requirements: functional.md
  - Use Cases: usecase.md
  - Data Modelling: DataModelling.md

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
plugins:
  - search
  - diagrams
  - render_swagger

